//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsMgmtAppFinal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactsMgmtAppFinal.ErrorRes", typeof(ErrorRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes?.
        /// </summary>
        internal static string editFormSave {
            get {
                return ResourceManager.GetString("editFormSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Please check again!.
        /// </summary>
        internal static string errMessageCaption {
            get {
                return ResourceManager.GetString("errMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a City.
        /// </summary>
        internal static string error_City {
            get {
                return ResourceManager.GetString("error_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Company Name.
        /// </summary>
        internal static string error_CN {
            get {
                return ResourceManager.GetString("error_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Country.
        /// </summary>
        internal static string error_Country {
            get {
                return ResourceManager.GetString("error_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid DOB.
        /// </summary>
        internal static string error_DOB {
            get {
                return ResourceManager.GetString("error_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Email Address.
        /// </summary>
        internal static string error_Email {
            get {
                return ResourceManager.GetString("error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a First Name.
        /// </summary>
        internal static string error_FN {
            get {
                return ResourceManager.GetString("error_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        internal static string error_InvalidEmail {
            get {
                return ResourceManager.GetString("error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Last Name.
        /// </summary>
        internal static string error_LN {
            get {
                return ResourceManager.GetString("error_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Not Found!.
        /// </summary>
        internal static string error_Load {
            get {
                return ResourceManager.GetString("error_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Nick Name.
        /// </summary>
        internal static string error_NN {
            get {
                return ResourceManager.GetString("error_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Postal Code.
        /// </summary>
        internal static string error_PC {
            get {
                return ResourceManager.GetString("error_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Phone Number.
        /// </summary>
        internal static string error_Phone {
            get {
                return ResourceManager.GetString("error_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Street Address.
        /// </summary>
        internal static string error_SA {
            get {
                return ResourceManager.GetString("error_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Street Number.
        /// </summary>
        internal static string error_SN {
            get {
                return ResourceManager.GetString("error_SN", resourceCulture);
            }
        }
    }
}
